# Generated by Django 5.0.6 on 2024-05-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="born_location",
            field=models.TextField(blank=True),
        ),
    ]
