# Generated by Django 5.0.6 on 2024-05-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0002_author_born_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="birth_date",
            field=models.CharField(blank=True, null=True),
        ),
    ]
